= DocBook
:groupId: io.github.oliviercailloux
:artifactId: docbook
:repository: DocBook

image:https://github.com/oliviercailloux/{artifactId}/workflows/Maven%20CI%20workflow/badge.svg["Maven CI", link="https://github.com/oliviercailloux/{repository}/actions"]
image:https://maven-badges.herokuapp.com/maven-central/{groupId}/{artifactId}/badge.svg["Artifact on Maven Central", link="https://central.sonatype.com/artifact/{groupId}/{artifactId}"]
image:http://www.javadoc.io/badge/{groupId}/{artifactId}.svg["Javadocs", link="http://www.javadoc.io/doc/{groupId}/{artifactId}"]

It seems that DocBook XSL 1 has https://github.com/docbook/xslt10-stylesheets/issues/234[never published] the latest version to Maven Central (differences https://github.com/docbook/xslt10-stylesheets/compare/release/1.79.1...release/1.79.2?diff=split&w=#diff-1e8dd53dd377fd3fca8f95fcbd1b891d2b762537f3c14aaeab02d54a8fb7a740[here]). Another problem is that the published version is a zip type dependency, which creates problems with Maven and IDEs.

This repository publishes the last version of DocBook XSL 1 to Maven Central.

== Clean
`mvn clean; rm -R src/main/resources/io/; rm -R doc/docbook/`

== Build
`mvn package`

== Zip dependencies in Maven
Invoking `mvn org.apache.maven.plugins:maven-dependency-plugin:3.8.1:build-classpath` includes the zip type dependency.
Invoking `mvn org.codehaus.mojo:exec-maven-plugin:3.5.0:java -Dexec.mainClass="…"` does not see the resources in the zip type (https://lists.apache.org/thread/h7bdsd6o9gbxqtsyq336rwrrr2zf1w4r[as expected], IIUC).

== Classified zip dependency in IDEs
vscode fails to see the zip type dependency with classifier in the classpath: the classpath that it builds automatically does not include it and it does not list this dependency in the project settings view.

IntelliJ IDEA also https://youtrack.jetbrains.com/issue/IDEA-148573/An-option-to-add-maven-artifacts-with-classifiers-into-classpath[seems to meet difficulties].
